#!/usr/bin/env python3
"""Build runtime locale catalogs from GNU gettext .po files.

Usage:
  scripts/build-locales.py compile   # po/*.po -> contents/ui/LocaleData.js
  scripts/build-locales.py extract   # scan QML/JS for tr()/trf()/trcp() -> po/*.pot
  scripts/build-locales.py sync      # extract, msgmerge into po/*.po, then compile

Community workflow: edit or add po/<lang>.po, then run compile (or sync).
"""

from __future__ import annotations

import argparse
import datetime as dt
import json
import re
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
PO_DIR = ROOT / "po"
UI_DIR = ROOT / "contents" / "ui"
LOCALE_DATA = UI_DIR / "LocaleData.js"
DOMAIN = "plasma_applet_com.local.openmeteo.weathercard"
POT_PATH = PO_DIR / f"{DOMAIN}.pot"

TR_CALL_RE = re.compile(
    r"""\b(?:tr|trf)\(\s*(?P<q>["'])(?P<text>(?:\\.|(?!\1).)*)(?P=q)"""
)
TRCP_CALL_RE = re.compile(
    r"""\btrcp\(\s*(?P<q1>["'])(?P<singular>(?:\\.|(?!\1).)*)(?P=q1)\s*,\s*(?P<q2>["'])(?P<plural>(?:\\.|(?!\2).)*)(?P=q2)"""
)
SCAN_GLOBS = (
    "contents/ui/**/*.qml",
    "contents/ui/**/*.js",
    "contents/config/**/*.qml",
)


def unescape_po(text: str) -> str:
    return (
        text.replace("\\\\", "\x00")
        .replace('\\"', '"')
        .replace("\\n", "\n")
        .replace("\\t", "\t")
        .replace("\x00", "\\")
    )


def escape_po(text: str) -> str:
    return (
        text.replace("\\", "\\\\")
        .replace('"', '\\"')
        .replace("\n", "\\n")
        .replace("\t", "\\t")
    )


def unescape_js(text: str) -> str:
    return (
        text.replace("\\\\", "\x00")
        .replace('\\"', '"')
        .replace("\\'", "'")
        .replace("\\n", "\n")
        .replace("\\t", "\t")
        .replace("\x00", "\\")
    )


def parse_po(path: Path) -> dict[str, str]:
    """Parse a simple gettext .po into msgid -> msgstr (skips empty/fuzzy msgstr)."""
    entries: dict[str, str] = {}
    msgid: list[str] | None = None
    msgstr: list[str] | None = None
    fuzzy = False

    def flush() -> None:
        nonlocal msgid, msgstr, fuzzy
        if msgid is None or msgstr is None:
            msgid = None
            msgstr = None
            fuzzy = False
            return
        key = unescape_po("".join(msgid))
        value = unescape_po("".join(msgstr))
        if key and value and not fuzzy:
            entries[key] = value
        msgid = None
        msgstr = None
        fuzzy = False

    for raw in path.read_text(encoding="utf-8").splitlines():
        line = raw.rstrip("\n")
        if line.startswith("#,"):
            fuzzy = "fuzzy" in line
            continue
        if line.startswith("#"):
            continue
        if line.startswith("msgid "):
            flush()
            msgid = [line[len("msgid ") :].strip()[1:-1]]
            msgstr = None
            continue
        if line.startswith("msgstr "):
            msgstr = [line[len("msgstr ") :].strip()[1:-1]]
            continue
        if line.startswith('"') and line.endswith('"'):
            chunk = line[1:-1]
            if msgstr is not None:
                msgstr.append(chunk)
            elif msgid is not None:
                msgid.append(chunk)
            continue
        if not line.strip():
            flush()

    flush()
    entries.pop("", None)
    return entries


def language_code_from_po(path: Path) -> str:
    text = path.read_text(encoding="utf-8")
    match = re.search(r'^"Language:\s*([^\\"]+)', text, re.MULTILINE)
    if match and match.group(1).strip():
        return match.group(1).strip().replace("-", "_")
    return path.stem


def write_locale_data(catalogs: dict[str, dict[str, str]]) -> None:
    generated = dt.datetime.now(dt.timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    body = json.dumps(catalogs, ensure_ascii=False, indent=2, sort_keys=True)
    content = (
        "// Generated by scripts/build-locales.py — do not edit by hand.\n"
        "// Source of truth: po/*.po\n"
        ".pragma library\n\n"
        f"var generatedAt = {json.dumps(generated)};\n"
        f"var catalogs = {body};\n"
    )
    LOCALE_DATA.write_text(content, encoding="utf-8")
    print(f"Wrote {LOCALE_DATA.relative_to(ROOT)} ({len(catalogs)} language(s))")


def compile_locales() -> int:
    catalogs: dict[str, dict[str, str]] = {}
    for path in sorted(PO_DIR.glob("*.po")):
        code = language_code_from_po(path)
        if code.lower() in {"en", "en_us", "c"}:
            print(f"Skip source-language catalog {path.name}")
            continue
        entries = parse_po(path)
        catalogs[code] = entries
        print(f"Loaded {path.name}: {len(entries)} strings -> {code}")
    if not catalogs:
        print("No .po catalogs found under po/", file=sys.stderr)
        return 1
    write_locale_data(catalogs)
    return 0


def collect_extra_msgids() -> list[str]:
    path = PO_DIR / "extra-msgids.txt"
    if not path.exists():
        return []
    found: list[str] = []
    for raw in path.read_text(encoding="utf-8").splitlines():
        line = raw.strip()
        if not line or line.startswith("#"):
            continue
        found.append(line)
    return found


def collect_source_msgids() -> list[str]:
    found: set[str] = set(collect_extra_msgids())
    for pattern in SCAN_GLOBS:
        for path in ROOT.glob(pattern):
            if path.name == "LocaleData.js":
                continue
            text = path.read_text(encoding="utf-8")
            for match in TR_CALL_RE.finditer(text):
                found.add(unescape_js(match.group("text")))
            for match in TRCP_CALL_RE.finditer(text):
                found.add(unescape_js(match.group("singular")))
                found.add(unescape_js(match.group("plural")))
    return sorted(found)


def write_pot(msgids: list[str]) -> None:
    PO_DIR.mkdir(parents=True, exist_ok=True)
    now = dt.datetime.now().strftime("%Y-%m-%d %H:%M%z")
    lines = [
        "# Translation template for Open-Meteo Weather Card.",
        "# Copyright (C) The package authors.",
        f"# Generated by scripts/build-locales.py on {now}",
        "#",
        'msgid ""',
        'msgstr ""',
        f'"Project-Id-Version: {DOMAIN}\\n"',
        '"Report-Msgid-Bugs-To: https://github.com/tiamed/plasma-openmeteo-weather/issues\\n"',
        f'"POT-Creation-Date: {now}\\n"',
        '"PO-Revision-Date: YEAR-MO-DA HO:MI+ZONE\\n"',
        '"Last-Translator: FULL NAME <EMAIL@ADDRESS>\\n"',
        '"Language-Team: LANGUAGE <LL@li.org>\\n"',
        '"Language: \\n"',
        '"MIME-Version: 1.0\\n"',
        '"Content-Type: text/plain; charset=UTF-8\\n"',
        '"Content-Transfer-Encoding: 8bit\\n"',
        '"Plural-Forms: nplurals=INTEGER; plural=EXPRESSION;\\n"',
        "",
    ]
    for msgid in msgids:
        lines.append(f'msgid "{escape_po(msgid)}"')
        lines.append('msgstr ""')
        lines.append("")
    POT_PATH.write_text("\n".join(lines), encoding="utf-8")
    print(f"Wrote {POT_PATH.relative_to(ROOT)} ({len(msgids)} strings)")


def extract() -> int:
    msgids = collect_source_msgids()
    if not msgids:
        print("No tr()/trf()/trcp() strings found", file=sys.stderr)
        return 1
    write_pot(msgids)
    return 0


def msgmerge_po_files() -> None:
    if not POT_PATH.exists():
        raise SystemExit(f"Missing template {POT_PATH}")
    for path in sorted(PO_DIR.glob("*.po")):
        subprocess.run(
            [
                "msgmerge",
                "--update",
                "--backup=none",
                "--no-fuzzy-matching",
                str(path),
                str(POT_PATH),
            ],
            check=True,
        )
        print(f"Merged {path.name}")


def sync() -> int:
    status = extract()
    if status != 0:
        return status
    msgmerge_po_files()
    return compile_locales()


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "command",
        choices=("compile", "extract", "sync"),
        help="compile: po->LocaleData.js; extract: scan->pot; sync: extract+merge+compile",
    )
    args = parser.parse_args()
    if args.command == "compile":
        return compile_locales()
    if args.command == "extract":
        return extract()
    return sync()


if __name__ == "__main__":
    sys.exit(main())
